[[main]]
    identifier = "home"
    name       = "ホーム"
    url        = "/ja/"
    weight     = -110
    [main.params]
        icon = "home"

[[main]]
    identifier = "about"
    name       = "について"
    url        = "/ja/about/"
    weight     = -90
    [main.params]
        icon = "user"

[[main]]
    identifier = "archives"
    name       = "アーカイブ"
    url        = "/ja/archives/"
    weight     = -70
    [main.params]
        icon = "archives"

# [[main]]
#     identifier = "links"
#     name       = "リンク"
#     url        = "/ja/links/"
#     weight     = -50
#     [main.params]
#         icon = "link"

[[main]]
    identifier = "search"
    name       = "検索"
    url        = "/ja/search/"
    weight     = -40
    [main.params]
        icon = "search"
